# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None

project_root = Path(r'C:/Users/Administrator/Desktop/weverse-stock-monitor')

added_files = [
    (str(project_root / "config.py"), "."),
    (str(project_root / "cookie_manager.py"), "."),
    (str(project_root / "crawler.py"), "."),
    (str(project_root / "gui.py"), "."),
    (str(project_root / "models.py"), "."),
    (str(project_root / "monitor.py"), "."),
    (str(project_root / "notifier.py"), "."),
    (str(project_root / "storage.py"), "."),
    (str(project_root / "weverse_crawler.py"), "."),
    (str(project_root / "data"), "data"),
]

hiddenimports = [
    "pandas",
    "pandas._libs.tslibs.base",
    "pandas._libs.tslibs.timedeltas",
    "pandas._libs.tslibs.timestamps",
    "pandas._libs.tslibs.np_datetime",
    "pandas._libs.tslibs.nattype",
    "pandas._libs.tslibs.timezones",
    "pandas._libs.tslibs.conversion",
    "pandas._libs.tslibs.fields",
    "pandas._libs.tslibs.vectorized",
    "pandas._libs.ops_dispatch",
    "pandas._libs.missing",
    "pandas._libs.lib",
    "pandas._libs.hashtable",
    "pandas._libs.index",
    "pandas._libs.algos",
    "pandas._libs.interval",
    "pandas._libs.join",
    "pandas._libs.reduction",
    "pandas._libs.reshape",
    "pandas._libs.sparse",
    "pandas._libs.writers",
    "pandas._libs.parsers",
    "pandas._libs.json",
    "pandas._libs.testing",
    "pandas._libs.hashing",
    "pandas.core.methods",
    "pandas.core._tools",
    "pandas.io.formats.style",
    "pandas.io.excel._openpyxl",
    "openpyxl",
    "openpyxl.cell._writer",
    "openpyxl.cell.cell",
    "openpyxl.styles",
    "openpyxl.styles.stylesheet",
    "openpyxl.utils",
    "openpyxl.workbook",
    "openpyxl.worksheet",
    "httpx",
    "httpx._transports.default",
    "httpcore",
    "httpcore._backends.sync",
    "httpcore._backends.anyio",
    "certifi",
    "idna",
    "sniffio",
    "h11",
    "h2",
    "hpack",
    "hyperframe",
    "anyio",
    "anyio._backends._trio",
    "anyio._backends._asyncio",
    "anyio.streams",
    "tkinter",
    "tkinter.filedialog",
    "tkinter.messagebox",
    "tkinter.ttk",
    "tkinter.scrolledtext",
    "xml.etree.ElementTree",
    "xml.etree.cElementTree",
]

a = Analysis(
    [str(project_root / "main.py")],
    pathex=[str(project_root)],
    binaries=[],
    datas=added_files,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="WeverseStockMonitor",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

app = BUNDLE(
    exe,
    name="WeverseStockMonitor.app",
    icon=None,
    bundle_identifier="com.weverse.stockmonitor",
    info_plist={
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1.0.0",
        "CFBundleDisplayName": "Weverse Stock Monitor",
        "CFBundleName": "WeverseStockMonitor",
        "NSHighResolutionCapable": True,
        "LSBackgroundOnly": False,
        "NSRequiresAquaSystemAppearance": False,
    },
)